#!/usr/bin/env bash
#
# The packaged shape: what an operator gets, not what a developer has.
#
#   tools/package_check.sh              build a tarball-shaped tree and boot it
#   tools/package_check.sh --keep       leave it behind for inspection
#
# WHY THIS EXISTS
#
# tools/check.sh runs in a developer checkout: addons/ is twelve symlinks into sibling
# repositories and ../game-simple-lobby is right there. Every configuration this project is
# actually SHIPPED in is the opposite -- a release tarball, and the container's final
# stage, which copies only this directory. In both of those the siblings are gone and
# the vendored copies are the only ones there will ever be.
#
# That difference is not cosmetic. A symlink out of addons/ dangles the moment the
# directory moves, every dot-* class_name is unresolved at once, and the server dies at
# startup with what reads as a broken project rather than as a dangling link -- the
# failure the Dockerfile's `--vendor` comment records having been found by running the
# container. Nothing re-checked it afterwards from this side.
#
# It also exercises the one branch check.sh deliberately does NOT fail on: with no
# ../game-simple-lobby to compare against, the lobby staleness check reports `--` and passes,
# because the copy it was built with is the only record. That branch has to keep
# working, and here is where it is reached on purpose rather than by accident.
#
# HOW IT WORKS
#
#   1. Exports the TRACKED files only, into a staging directory beside symlinks to the
#      sibling repositories. Tracked-only on purpose: addons/, game/ and scenes/ are
#      gitignored here, so anything left in a working tree would hide the case where
#      setup.sh fails to produce them.
#   2. Runs ./setup.sh --vendor there -- the developer-builds-a-tarball position.
#   3. MOVES the result somewhere the siblings do not exist, which is the shape an
#      operator unpacks, and checks nothing points back out of it.
#   4. Boots it for real.
#
# It does not build the container. That needs a Docker daemon; this needs bash and the
# same Godot everything else here uses.

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT="$PWD"

GODOT="${GODOT:-godot}"
RED=$'\033[31m'; GRN=$'\033[32m'; OFF=$'\033[0m'
fails=0
KEEP=0
[ "${1:-}" = "--keep" ] && KEEP=1

pass() { printf '  %sok%s   %s\n' "$GRN" "$OFF" "$1"; }
fail() { printf '  %sFAIL%s %s\n' "$RED" "$OFF" "$1"; fails=$((fails + 1)); }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/tmc-package.XXXXXX")" || exit 1
cleanup() {
    if [ "$KEEP" -eq 1 ]; then
        printf '\nleft behind: %s\n' "$WORK"
    else
        chmod -R u+w "$WORK" 2>/dev/null
        rm -rf "$WORK"
    fi
}
trap cleanup EXIT

STAGE="$WORK/build"
SHIP="$WORK/ship"
mkdir -p "$STAGE" "$SHIP" || exit 1

# --- 1. Stage the tracked files, siblings in reach -------------------------

echo "staging"

# The sibling repositories, as links rather than copies: setup.sh --vendor uses
# `cp -rL`, so what lands in addons/ is real content either way, and this costs
# nothing to set up.
#
# [b]Read out of setup.sh, not written down again.[/b] This was a third hand-kept copy
# of the same knowledge and it had drifted like the other two: it still named
# `dot-a-room`, and it was missing every addon added since — so the staged tree was
# vendored without them and the packaged check passed on a build the real one could not
# make. setup.sh is the one place that knows what this project is made of.
mapfile -t STAGE_REPOS < <(
    {
        sed -n '/^ADDONS=(/,/)/p' "$ROOT/setup.sh" | grep -oE 'dot_[a-z0-9_]+' | tr '_' '-'
        sed -n '/^GAMES=(/,/^)/p' "$ROOT/setup.sh" | grep -oE '"[^"]+"' | tr -d '"' | cut -d: -f1
    } | sort -u
)

[ ${#STAGE_REPOS[@]} -gt 0 ] || fail "could not read the repository list out of setup.sh"

for repo in "${STAGE_REPOS[@]}"; do
    if [ -d "$ROOT/../$repo" ]; then
        ln -s "$(cd "$ROOT/../$repo" && pwd)" "$STAGE/$repo"
    else
        fail "../$repo is not beside this repository; nothing to vendor from"
    fi
done
[ "$fails" -eq 0 ] || { echo; printf '%s%d failed%s\n' "$RED" "$fails" "$OFF"; exit 1; }

mkdir -p "$STAGE/dot-server-deploy"
if (cd "$ROOT" && git ls-files -z | tar --null -T - -cf -) \
    | tar -xf - -C "$STAGE/dot-server-deploy"; then
    pass "$(git -C "$ROOT" ls-files | wc -l) tracked files exported"
else
    fail "could not export the tracked files"
    echo; printf '%s%d failed%s\n' "$RED" "$fails" "$OFF"; exit 1
fi

# Nothing gitignored may have come along, or the rest of this proves nothing.
for gone in addons game scenes; do
    if [ -e "$STAGE/dot-server-deploy/$gone" ]; then
        fail "$gone/ is tracked; it is meant to be generated by setup.sh"
    fi
done

# --- 2. Vendor ------------------------------------------------------------

echo
echo "setup.sh --vendor"

if (cd "$STAGE/dot-server-deploy" \
    && ./setup.sh --godot "$(command -v "$GODOT" || echo "$GODOT")" --vendor) \
    >"$WORK/setup.log" 2>&1; then
    pass "vendored and imported"
else
    fail "./setup.sh --vendor"
    sed 's/^/       /' "$WORK/setup.log" | tail -20
    echo; printf '%s%d failed%s\n' "$RED" "$fails" "$OFF"; exit 1
fi

# --- 3. Move it away from the siblings ------------------------------------

echo
echo "the shipped tree"

mv "$STAGE/dot-server-deploy" "$SHIP/tmc-server" || exit 1
rm -rf "$STAGE"
TREE="$SHIP/tmc-server"

# The whole point. A dangling link here is every dot-* class_name unresolved at once.
dangling="$(find "$TREE" -xtype l | sed "s|^$TREE/||")"
if [ -z "$dangling" ]; then
    pass "nothing in the tree points outside it"
else
    fail "dangling symlinks after the move:"
    printf '       %s\n' $dangling
fi

# addons/ must be real directories. A surviving symlink is the developer shape that
# happens to still resolve because the move landed near the siblings.
linked="$(find "$TREE/addons" -maxdepth 1 -type l 2>/dev/null | sed "s|^$TREE/||")"
if [ -z "$linked" ]; then
    pass "$(find "$TREE/addons" -maxdepth 1 -mindepth 1 -type d | wc -l) addons are real directories"
else
    fail "addons/ still holds symlinks:"
    printf '       %s\n' $linked
fi

# The lobby is copied out of ../game-simple-lobby, which is now gone. It has to have come
# with the tree.
if [ -f "$TREE/scenes/room_server.tscn" ] && [ -d "$TREE/game" ]; then
    pass "the lobby travelled with it ($(find "$TREE/game" "$TREE/scenes" -name '*.gd' -o -name '*.tscn' | wc -l) files)"
else
    fail "game/ or scenes/ did not survive the move"
fi

# --- 4. It runs -----------------------------------------------------------

echo
echo "the staleness branch"

# check.sh --parse with no sibling to compare against: the lobby check reports `--`
# and must NOT fail, because in this shape the copy is the only record there is. It is
# the one branch of check.sh a developer checkout can never reach.
parse_out="$( (cd "$TREE" && GODOT="$GODOT" tools/check.sh --parse) 2>&1 )"
parse_rc=$?

if [ "$parse_rc" -eq 0 ]; then
    pass "check.sh --parse passes with no ../game-simple-lobby"
else
    fail "check.sh --parse in the shipped tree"
    printf '%s\n' "$parse_out" | sed 's/^/       /' | tail -20
fi

if printf '%s' "$parse_out" | grep -q 'staleness not checked'; then
    pass "and says the lobby could not be compared, rather than passing silently"
else
    fail "the missing-sibling notice is gone from check.sh"
fi

echo
echo "booting"

if (cd "$TREE" && ./server check) >"$WORK/boot.log" 2>&1; then
    pass "the server boots, loads the lobby, and shuts down"
else
    fail "./server check in the shipped tree"
    sed 's/^/       /' "$WORK/boot.log" | tail -25
fi

echo
if [ "$fails" -eq 0 ]; then
    printf '%sthe packaged shape works%s\n' "$GRN" "$OFF"
else
    printf '%s%d failed%s\n' "$RED" "$fails" "$OFF"
fi
exit $((fails > 0))
